specVersion: 1.0.0
name: subql-nodle
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: 'Subquery indexer for Nodle network (testnet).'
repository: https://github.com/NodleCode/subquery.git
schema:
  file: ./schema.graphql
network:
  chainId: '0x0fd167da222f10dae826a0433fe4daadcf4a36c2a6bd5c1b085857d5b79030af'
  endpoint: wss://nodle-paradis.api.onfinality.io/public-ws
chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBalanceTransferEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleBalanceTransferEventChainState
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleBalanceDepositEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleVestingScheduleAddedEvent
          kind: substrate/EventHandler
          filter:
            module: vesting
            method: VestingScheduleAdded
        - handler: handleUniquesTransferEvent
          kind: substrate/EventHandler
          filter:
            module: uniques
            method: Transferred
        - handler: handleNewAccountEvent
          kind: substrate/EventHandler
          filter:
            module: system
            method: NewAccount
        - handler: handleKilledAccountEvent
          kind: substrate/EventHandler
          filter:
            module: system
            method: KilledAccount
        - handler: handleCancelAllVestingSchedulesCall
          kind: substrate/CallHandler
          filter:
            module: vesting
            method: cancelAllVestingSchedules
        - handler: handleAllocationBatchCall
          kind: substrate/CallHandler
          filter:
            module: allocations
            method: batch

