specVersion: 0.2.0
name: subql-nodle
version: 0.0.4
description: This project can be use as a starting po...
repository: https://github.com/hobbydev71/subquery-nodle.git
schema:
  file: ./schema.graphql
network:
  endpoint: wss://nodle-parachain.api.onfinality.io/public-ws
  genesisHash: '0x97da7ede98d7bad4e36b4d734b6055425a3be036da2a332ea5a7037656427a21'
dataSources:
  - kind: substrate/Runtime
    startBlock: 343031
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
        - handler: systemTokenTransferEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
