specVersion: 0.2.0
name: subql-nodle
version: 0.0.4
description: This project can be use as a starting po...
repository: https://github.com/hobbydev71/subquery-nodle.git
schema:
  file: ./schema.graphql
network:
  endpoint: wss://nodle.api.onfinality.io/public-ws
  genesisHash: '0xa3d114c2b8d0627c1aa9b134eafcf7d05ca561fdc19fb388bb9457f81809fb23'
dataSources:
  - kind: substrate/Runtime
    startBlock: 334991
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
        - handler: systemTokenTransferEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
