specVersion: 1.0.0
name: subql-nodle
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: 'Subquery indexer for Nodle network (testnet).'
repository: https://github.com/NodleCode/subquery.git
schema:
  file: ./schema.graphql
network:
  chainId: '0x0fd167da222f10dae826a0433fe4daadcf4a36c2a6bd5c1b085857d5b79030af'
  endpoint: wss://nodle-paradis.api.onfinality.io/ws?apikey=7dd34ba4-6fa7-466d-ad89-001c6b603220
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: systemTokenTransferEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleVestingScheduleAdded
          kind: substrate/EventHandler
          filter:
            module: vesting
            method: VestingScheduleAdded
        - handler: uniquesTransferEvent
          kind: substrate/EventHandler
          filter:
            module: uniques
            method: Transferred
        - handler: handleAllocation
          kind: substrate/CallHandler
          filter:
            module: allocations
            method: batch

