specVersion: 1.0.0
name: subql-nodle
version: 0.0.4
runner:
  node:
    name: '@subql/node'
    version: 1.2.1
  query:
    name: '@subql/query'
    version: latest
description: This project can be use as a starting po...
repository: https://github.com/NodleCode/subquery.git
schema:
  file: ./schema.graphql
network:
  chainId: '0x97da7ede98d7bad4e36b4d734b6055425a3be036da2a332ea5a7037656427a21'
  endpoint: wss://nodle-parachain.api.onfinality.io/public-ws
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 304775
    mapping: 
      file: ./dist/index.js
      handlers:
        - handler: systemTokenTransferEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleVestingSchedule
          kind: substrate/CallHandler
          filter:
            module: vesting
            method: addVestingSchedule
