specVersion: 1.0.0
name: subql-nodle
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: 'Subquery indexer for Nodle network (testnet).'
repository: https://github.com/NodleCode/subquery.git
schema:
  file: ./schema.graphql
network:
  chainId: '0x0fd167da222f10dae826a0433fe4daadcf4a36c2a6bd5c1b085857d5b79030af'
  endpoint: wss://nodle-paradis.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/NodleCode/nodle-testnet-dictionary
chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1088055
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleUniquesTransferEvent
          kind: substrate/EventHandler
          filter:
            module: uniques
            method: Transferred
        - handler: handleUniquesMetadataSetEvent
          kind: substrate/EventHandler
          filter:
            module: uniques
            method: MetadataSet
        - handler: handleUniquesCollectionMetadataSetEvent
          kind: substrate/EventHandler
          filter:
            module: uniques
            method: CollectionMetadataSet
        - handler: handleBalanceTransferEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleAllocationBatchCall
          kind: substrate/CallHandler
          filter:
            module: allocations
            method: batch
