name: Build and Push Container Image

on:
  pull_request:
    types:
      - labeled
  push:
    branches:
      - main
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      id-token: write

    env:
      REGION: us-central1

    steps:
      - uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          install_components: beta

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Authenticate to Artifact Registry
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build Container Image
        run: |-
          docker build \
            -f Dockerfile \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/service/subql-node:${GITHUB_SHA} \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/service/subql-node:${GITHUB_REF//\//-} .

      - name: Publish Container Image
        run: |-
          docker push -a ${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/service/subql-node
